package main

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/sitehostnz/gosh/pkg/api/cloud/stack"
)

// stepStack deploys a website container and fetches it from outside.
//
// # Why this runs before the SSH user
//
// cloud/ssh/user/add.json rejects an account with no containers and no
// volumes: "Please specify a valid list of volumes or containers." So a
// container SSH user cannot exist before there is a container to grant
// it, and the stack has to come first. The first version of this
// journey had these two steps the other way round and step 30 failed on
// a healthy server.
//
// # This is the check the control plane cannot give you
//
// A stack's reported state is "Up" once the platform has started the
// container. That is not the same as the container serving anything.
// The two come apart in the ways that matter — an image that starts and
// exits, a compose file the platform accepted and Docker did not, a
// service listening on the wrong port — and in every one of them the
// API still says Up.
//
// So this step makes an HTTP request from wherever the example runs and
// requires an answer. The mechanism is worth stating because it is
// undocumented and it is what makes the check possible at all:
//
//   - A container server publishes tcp/80 and tcp/443.
//   - Those ports are served by a reverse proxy on the host, which
//     routes by Host header using each container's VIRTUAL_HOST
//     environment variable.
//   - "*.<ip>.sth.nz" resolves to the container server holding <ip>, so
//     a stack that sets VIRTUAL_HOST=<label>.<ip>.sth.nz is reachable
//     by that name with no DNS work.
//
// Setting VIRTUAL_HOST is therefore not decoration in the compose file
// below; it is the whole routing contract. A stack without it deploys
// successfully and is unreachable.
//
// # The compose file has to match what the platform expects
//
// The service key, container_name and the nz.sitehost.container.label
// label all carry the generated stack name, and the type label marks it
// as a website container. This mirrors what the platform's own tooling
// writes. "expose" rather than "ports": the proxy reaches the container
// over the Docker network, so publishing to the host is unnecessary and
// would collide between stacks.
func stepStack(ctx context.Context, c clients, st *state) error {
	name, err := subject(st)
	if err != nil {
		return err
	}
	if err := ensureAddress(ctx, c, st, name); err != nil {
		return err
	}

	// The stack name is generated by the platform rather than chosen.
	// It is also the container name and the compose service key, so
	// asking for it first is simpler than inventing one and finding out
	// it collided.
	time.Sleep(throttle)
	gen, err := c.stack.GenerateName(ctx)
	if err != nil {
		return fmt.Errorf("stack.GenerateName: %w", err)
	}
	if gen.Return.Name == "" {
		return fmt.Errorf("stack.GenerateName: returned no name")
	}
	st.stackName = gen.Return.Name
	st.stackHost = fmt.Sprintf("%s.%s.sth.nz", st.stackName, st.ip)
	log.Printf("✓ generated stack name %q, routable as %s", st.stackName, st.stackHost)

	if err := deployStack(ctx, c, st, name); err != nil {
		return err
	}
	// Serving is proven in step 40, which is the first point at which a
	// shell exists to reach the container directly. Reported here so a
	// standalone run of this step still says what the outside sees.
	reportPublicRouting(st)
	return nil
}

// composeFor builds the compose file for a single website container.
//
// This mirrors what the platform's own tooling writes, and two parts of
// it are load-bearing in ways nothing documents:
//
//   - The external "infra_default" network. The reverse proxy that
//     serves ports 80 and 443 lives on it, so a container that does not
//     join it cannot be routed to at all. Omitting this section
//     produced a stack whose container reported state Up while every
//     request returned the proxy's own 503 — which looks exactly like a
//     broken application and is not.
//   - The /container/* volumes. The image serves from
//     /container/application, so without them there is no docroot to
//     write into and step 50 has nowhere to put its probe page.
//
// VIRTUAL_HOST is what the proxy routes on. The vhosts label carries
// the same value for the control panel's benefit; the routing follows
// the environment variable.
//
// # Ports: what a web container can and cannot do
//
// Documented at https://kb.sitehost.nz/cloud-containers/containers/ports
// — read that before this comment, which only adds what the API does
// when you get it wrong.
//
// "expose" rather than "ports", and the reason is the container's type
// rather than a limit on the API.
//
// Web and application containers cannot have their ports changed at
// all: 80 and 443 are open by default and that is the whole of it. This
// was established the expensive way before reading the documentation
// that says so — a stack deployed with "ports: - '8931:80/tcp'" was
// accepted, returned a job that completed, kept the mapping when read
// back through cloud/stack/get.json, and came up with state Up, while
// the port stayed closed from outside both before and after
// cloud/stack/restart.json completed. cloud/stack/get.json reports the
// container's own "ports" as null throughout, which is the only hint
// the API gives.
//
// Service containers are the ones that publish. Redis, Postgres,
// MongoDB, Elasticsearch, Solr and the rest ship with their port
// exposed and unpublished, and publishing it is supported — subject to
// rules worth knowing before choosing a number:
//
//   - below 1024 is reserved and refused;
//   - 3306 to 3310 and 8080 are refused specifically, which catches
//     the NodeJS images, since 8080 is the port they expose;
//   - a published port must be unique across the containers on a
//     server.
//
// Security groups are not applied to Cloud Containers, so the mechanism
// examples/server uses to open a port on a virtual server does nothing
// here — the publish decision is the whole of it.
//
// Why this matters rather than being trivia: the use cases are real and
// they are not web traffic. An MQTT broker, a game server or a mail
// service speaks a protocol the reverse proxy in front of 80 and 443
// cannot carry, so a published port is the only route. WebSockets are
// the exception that misleads, since they upgrade from HTTP and the
// proxy carries them without one. And a database reachable from
// outside is a different question again: those live in integrated
// containers, which these endpoints do not manage, and their ports are
// in the refused range anyway.
func composeFor(st *state) string {
	root := "/data/docker0/www/" + st.stackName
	return strings.Join([]string{
		"version: '2.1'",
		"services:",
		"    " + st.stackName + ":",
		"        container_name: " + st.stackName,
		"        environment:",
		"            - 'VIRTUAL_HOST=" + st.stackHost + "'",
		"        expose:",
		"            - 80/tcp",
		"        image: 'registry.sitehost.co.nz/sitehost-php85-apache:1.0.0-noble'",
		"        labels:",
		"            - nz.sitehost.container.label=" + st.stackHost,
		"            - nz.sitehost.container.type=www",
		"            - nz.sitehost.container.monitored=True",
		"            - 'nz.sitehost.container.website.vhosts=" + st.stackHost + "'",
		"        restart: unless-stopped",
		"        volumes:",
		"            - '" + root + "/config:/container/config:ro'",
		"            - '" + root + "/logs:/container/logs:rw'",
		"            - '" + root + "/crontabs:/cron:ro'",
		"            - '" + root + "/application:/container/application:rw'",
		"            - '" + root + "/system:/container/system:rw'",
		"networks:",
		"    default:",
		"        external:",
		"            name: infra_default",
		"",
	}, "\n")
}

// deployStack creates the stack and waits for the build.
func deployStack(ctx context.Context, c clients, st *state, name string) error {
	time.Sleep(throttle)
	resp, err := c.stack.Add(ctx, stack.AddRequest{
		ServerName:    name,
		Name:          st.stackName,
		Label:         st.stackHost,
		EnableSSL:     0,
		DockerCompose: composeFor(st),
	})
	if err != nil {
		return fmt.Errorf("stack.Add(%s): %w", st.stackName, err)
	}
	log.Printf("✓ requested stack %q (job %d)", st.stackName, resp.Return.ID)

	if err := waitJob(ctx, c.job, resp.Return.Job); err != nil {
		return fmt.Errorf("stack.Add(%s): %w", st.stackName, err)
	}

	time.Sleep(throttle)
	got, err := c.stack.Get(ctx, stack.GetRequest{ServerName: name, Name: st.stackName})
	if err != nil {
		return fmt.Errorf("stack.Get(%s): %w", st.stackName, err)
	}
	log.Printf("  control plane reports stack %q with %d container(s)", got.Stack.Name, len(got.Stack.Containers))
	for _, ct := range got.Stack.Containers {
		log.Printf("    container %s state=%s image=%s", ct.Name, ct.State, ct.Image)
	}
	return nil
}

// reportPublicRouting records whether the stack is reachable from
// outside, without asserting it.
//
// # The routing contract
//
// "*.<ip>.sth.nz" resolves to the container server, a proxy on the host
// serves ports 80 and 443, and it routes by Host header using each
// container's VIRTUAL_HOST. A stack that sets VIRTUAL_HOST is therefore
// reachable by that name with no DNS work — and one deployed by this
// step was fetched over its public hostname and answered 200.
//
// # Why it is reported rather than asserted
//
// It was also observed failing, in a way worth recording because the
// obvious reading is wrong. In sequence, on one server:
//
//   - A stack deployed WITHOUT the external infra_default network came
//     up with its container reported Up, and its public hostname
//     returned the proxy's 503.
//   - A second stack, this time with the network, also returned 503
//     publicly for over ninety seconds — while serving correctly when
//     fetched by stack name over the Docker network from inside the
//     host.
//   - The first stack was deleted. The next stack deployed the same way
//     as the second answered 200 publicly, immediately.
//
// So the public 503 tracked the presence of the malformed stack rather
// than the API being unable to publish anything, which was the first
// conclusion drawn here and was wrong. A stack that cannot be routed to
// appears to cost the ones alongside it, not only itself. That is a
// correlation across three deploys and not a proven mechanism, so it is
// written down as an observation.
//
// Asserting the public fetch would make this step fail for that state
// rather than for anything the SDK did, and the container's own serving
// is proven directly in step 40. Hence: reported.
func reportPublicRouting(st *state) {
	url := "http://" + st.stackHost + "/"
	code, _, err := httpGetStatus(url)
	switch {
	case err != nil:
		log.Printf("  public %s did not answer: %v", url, err)
	case gatewayError(code):
		log.Printf("  public %s answers HTTP %d — the host proxy has no route to this stack; step 40 checks the container directly", url, code)
	default:
		log.Printf("  public %s answers HTTP %d", url, code)
	}
}
